baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'John Doe - C# Developer Portfolio'
theme = 'csharp-portfolio'

# Enable syntax highlighting
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = false
    anchorLineNos = false
    lineAnchors = ""
    lineNoStart = 1
    hl_Lines = ""

# Theme parameters
[params]
  # Personal information
  author = "John Doe"
  description = "Senior C# developer with 8+ years of experience building scalable web applications and APIs"

  # Theme settings
  [params.theme]
    defaultMode = "auto"
    enableToggle = true
    enableTypingAnimation = true

  # Hero section
  [params.hero]
    title = "Hello, World!"
    subtitle = "// Senior C# developer specializing in .NET and cloud architecture"
    showTypingAnimation = true

  # About section
  [params.about]
    description = """
I'm a passionate **Senior C# Developer** with over 8 years of experience building robust, scalable applications.
I specialize in **ASP.NET Core**, **microservices architecture**, and **cloud-native development** on Microsoft Azure.

My approach to development is rooted in **clean code principles**, **test-driven development**, and **continuous learning**.
I believe that great software is not just functional—it's maintainable, testable, and a joy to work with.
"""
    profileImage = "/images/profile.jpg"
    experience = 8
    projects = 75
    available = true

    # Skills displayed as C# using statements
    [[params.about.skills]]
      category = "Microsoft"
      name = "AspNetCore"

    [[params.about.skills]]
      category = "Microsoft"
      name = "EntityFrameworkCore"

    [[params.about.skills]]
      category = "System"
      name = "Linq"

    [[params.about.skills]]
      category = "Microsoft"
      name = "Azure"

    [[params.about.skills]]
      category = "React"
      name = "Components"

    [[params.about.skills]]
      category = "TypeScript"
      name = "Definitions"

    # Extended skill categories for about page
    [[params.about.skillCategories]]
      name = "Backend"
      category = "Backend"
      skills = ["C#", "ASP.NET Core", "Entity Framework", "SQL Server", "Azure Functions", "SignalR"]

    [[params.about.skillCategories]]
      name = "Frontend"
      category = "Frontend"
      skills = ["React", "TypeScript", "HTML5", "CSS3", "Blazor", "JavaScript"]

    [[params.about.skillCategories]]
      name = "Cloud & DevOps"
      category = "Cloud"
      skills = ["Microsoft Azure", "Docker", "Kubernetes", "Azure DevOps", "ARM Templates", "Bicep"]

    [[params.about.skillCategories]]
      name = "Tools & IDEs"
      category = "Tools"
      skills = ["JetBrains Rider", "Visual Studio", "VS Code", "Git", "Postman", "Azure Data Studio"]

  # Social links
  [params.social]
    github = "johndoe"
    linkedin = "johndoe-dev"
    twitter = "johndoe_dev"
    email = "john.doe@example.com"

  # SEO settings
  [params.seo]
    description = "Senior C# Developer portfolio showcasing expertise in .NET, Azure, and modern web development"
    keywords = ["C#", ".NET", "ASP.NET Core", "Azure", "developer", "portfolio", "full-stack", "microservices"]
    author = "John Doe"

  # Performance settings
  [params.performance]
    inlineCriticalCSS = true
    fontDisplaySwap = true
    minifyAssets = true

# Menu configuration
[menu]
  [[menu.main]]
    name = "Portfolio.About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Portfolio.Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    name = "Portfolio.Skills"
    url = "/skills/"
    weight = 30

  [[menu.main]]
    name = "Portfolio.Contact"
    url = "/contact/"
    weight = 40

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  technology = "technologies"